# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _my_lib
else:
    import _my_lib

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class my_api_requester(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, callback):
        _my_lib.my_api_requester_swiginit(self, _my_lib.new_my_api_requester(callback))
    __swig_destroy__ = _my_lib.delete_my_api_requester

    def open(self):
        return _my_lib.my_api_requester_open(self)

    def close(self):
        return _my_lib.my_api_requester_close(self)

    def sub_marketdata(self, contract):
        return _my_lib.my_api_requester_sub_marketdata(self, contract)

    def query_order_books(self, symbol):
        return _my_lib.my_api_requester_query_order_books(self, symbol)

# Register my_api_requester in _my_lib:
_my_lib.my_api_requester_swigregister(my_api_requester)
class my_api_responder(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _my_lib.delete_my_api_responder

    def on_query_order_books(self, order_id, symbol, qty, price):
        return _my_lib.my_api_responder_on_query_order_books(self, order_id, symbol, qty, price)

    def on_sub_marketdata_rsp(self, symbol, ret):
        return _my_lib.my_api_responder_on_sub_marketdata_rsp(self, symbol, ret)

    def __init__(self):
        if self.__class__ == my_api_responder:
            _self = None
        else:
            _self = self
        _my_lib.my_api_responder_swiginit(self, _my_lib.new_my_api_responder(_self, ))
    def __disown__(self):
        self.this.disown()
        _my_lib.disown_my_api_responder(self)
        return weakref.proxy(self)

# Register my_api_responder in _my_lib:
_my_lib.my_api_responder_swigregister(my_api_responder)

